### ISSUE TITLE
Support for cheeriojs?

### ISSUE THREAD

**Issue by NKjoep** [Runscope/script-libraries#5]
Hello,

Do you have support for [cheerio](https://github.com/cheeriojs/cheerio) in your platform?
If not, do you have any advice on how to _validate_ or parse html fragments from the response?

We have tests with mixed apis returning both json and html and I was wondering what is the best way to extract values from the html strings.
For that purpose I usually cheerio with nodejs in my tests and we'd like to move those tests to Runscope.

**Comment by zdumitru** [comment]
@NKjoep What I do is save HTML response as a variable and then using regex extract needed parts and validate or modify them. For this I use post-response script. But I agree, would be easier to have some kind of integration that helps you modify and parse HTML pages.

**Comment by NKjoep** [comment]
That's what I thought. The plain regexp approach doesn't feel very robust and developer friendly to me. It might be very difficult to extract some values depending on the html tree.

Xpath also is a nightmare :)

**Comment by NKjoep** [comment]
Side note: I managed to make [himalaya](https://github.com/andrejewski/himalaya) work in my tests. 

I've built it without sourcemaps and added it as a script in my tests. Still better than marked which sometimes returns incorrect objects.

**Comment by heitortsergent** [comment]
@NKjoep I'm glad you got himalaya working! (and thanks for jumping in with your feedback @zdumitru)

@NKjoep did you try to get the cheerio library working too? Would you be interested in opening up a PR for the himalaya library you got working? It could be helpful to other users too. :)

**Comment by NKjoep** [comment]
Please see #6

**Comment by heitortsergent** [comment]
Will do, thanks @NKjoep. I'm going to close this issue then.
